---
- name: "Skip SSH client setup on Windows"
  ansible.builtin.debug:
    msg: "SSH client provisioning is not yet implemented for Windows"
  when: ansible_os_family == "Windows"

- name: "Determine SSH client packages"
  ansible.builtin.set_fact:
    setup_ssh_client_packages: "{{ ssh_client_packages.get(ansible_distribution) | default(['openssh-client']) }}"
  when: ansible_os_family != "Windows"

- name: "Install SSH client packages"
  ansible.builtin.package:
    name: "{{ setup_ssh_client_packages }}"
    state: present
  become: true
  when: ansible_os_family != "Windows"

- name: "Ensure ~/.ssh directory exists"
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0700"
  when: ansible_os_family != "Windows"

- name: "Ensure vault variables are present"
  ansible.builtin.assert:
    that:
      - vault_ssh_private_key is defined
      - vault_ssh_public_key is defined
    fail_msg: "SSH vault secrets are missing. Run tools/refresh-secrets or update group_vars/all/vault.yml."
  when: ansible_os_family != "Windows"

- name: "Install SSH private key"
  ansible.builtin.copy:
    content: "{{ vault_ssh_private_key }}\n"
    dest: "{{ ssh_dir }}/id_ed25519"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0600"
  no_log: true
  when: ansible_os_family != "Windows"

- name: "Install SSH public key"
  ansible.builtin.copy:
    content: "{{ vault_ssh_public_key }}\n"
    dest: "{{ ssh_dir }}/id_ed25519.pub"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0644"
  when: ansible_os_family != "Windows"
